# Анализ метрик полученных из Prometheus с помощью машинного обучения
### Загрузка модуля $sktime$ 

In [ ]:
!pip install sktime

### Импорт необходимых модулей

In [ ]:
import os
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

from sktime.classification.compose import ColumnEnsembleClassifier
from sktime.classification.distance_based import KNeighborsTimeSeriesClassifier
from sktime.classification.interval_based import TimeSeriesForestClassifier
from sktime.transformations.panel.compose import ColumnConcatenator
from sktime.datatypes._panel._convert import from_2d_array_to_nested

### Загрузка данных

#### Считывание данных, полученных с помощью Prometheus с виртуальных машин (train)
Данные собраны в 3 состояниях:
- "Пустое" состояние
- Состояние повышенной нагрузки (с помощью утилиты stress)
- Состояние полезной нагрузки (работает Prometheus)

файлы diam_\*, rept_\* - зараженные \\
Файлы free_\* - чистые

In [ ]:
fd = []
fd.append(pd.read_csv('/content/drive/MyDrive/curs_work/train/diam_1.csv', index_col=0))
fd.append(pd.read_csv('/content/drive/MyDrive/curs_work/train/diam_2.csv', index_col=0))
fd.append(pd.read_csv('/content/drive/MyDrive/curs_work/train/diam_3.csv', index_col=0))
fd.append(pd.read_csv('/content/drive/MyDrive/curs_work/train/rept_1.csv', index_col=0))
fd.append(pd.read_csv('/content/drive/MyDrive/curs_work/train/rept_2.csv', index_col=0))
fd.append(pd.read_csv('/content/drive/MyDrive/curs_work/train/rept_3.csv', index_col=0))
fd.append(pd.read_csv('/content/drive/MyDrive/curs_work/train/free_1.csv', index_col=0))
fd.append(pd.read_csv('/content/drive/MyDrive/curs_work/train/free_2.csv', index_col=0))
fd.append(pd.read_csv('/content/drive/MyDrive/curs_work/train/free_3.csv', index_col=0))

Разобьем данные с каждой ВМ на 3 части, для дальнейшего обучения

In [ ]:
enlarged = []
for i in fd:
    enlarged.append(i.iloc[np.arange(0,40)])
    enlarged.append(i.iloc[np.arange(40,80)].reset_index(drop=True))
    enlarged.append(i.iloc[np.arange(80,120)].reset_index(drop=True))

##### Перевод данных из pandas DataFrame в тип данных, необходимый для работы с модулем sktime

In [ ]:
sk_frame = from_2d_array_to_nested(enlarged[0].T).T
for i in np.arange(1, len(enlarged)):
    sk_frame = sk_frame.append(from_2d_array_to_nested(enlarged[i].T).T)

In [ ]:
sk_frame.columns = enlarged[0].columns
sk_frame = sk_frame.reset_index(drop=True)
sk_frame = sk_frame.reindex(np.concatenate((np.arange(0,27,3), np.arange(1,27,3), np.arange(2,27,3))))
sk_frame = sk_frame.reset_index(drop=True)
sk_frame.head(5)


libvirt_domain_block_stats_flush_requests_total  \
0  0     51896.0
1     51896.0
2     51908.0
3   ...   
1  0     24780672.0
1     26145937.0
2     276454...   
2  0     217333486.0
1     217333494.0
2     2173...   
3  0     52634.0
1     52638.0
2     52638.0
3   ...   
4  0     15871504.0
1     17405784.0
2     190254...   

  libvirt_domain_block_stats_flush_time_seconds_total  \
0  0     3.812795
1     3.812795
2     3.814651
3...    
1  0     208.361958
1     219.678610
2     232.07...    
2  0     1745.715011
1     1745.716272
2     1745...    
3  0     3.719479
1     3.720177
2     3.720177
3...    
4  0     131.631761
1     143.894649
2     156.57...    

         libvirt_domain_block_stats_read_bytes_total  \
0  0     1.046134e+09
1     1.046134e+09
2     1....   
1  0     1.107918e+09
1     1.107918e+09
2     1....   
2  0     1.290030e+09
1     1.290067e+09
2     1....   
3  0     961037312.0
1     961037312.0
2     9610...   
4  0     980214784.0
1     980214784.0
2     9802...   

      libvirt_domain_block_stats_read_requests_total  \
0  0     48260.0
1     48260.0
2     48260.0
3   ...   
1  0     60581.0
1     60581.0
2     60581.0
3   ...   
2  0     62469.0
1     62473.0
2     62473.0
3   ...   
3  0     44975.0
1     44975.0
2     44975.0
3   ...   
4  0     46481.0
1     46481.0
2     46481.0
3   ...   

  libvirt_domain_block_stats_read_time_seconds_total  \
0  0     140.977919
1     140.977919
2     140.97...   
1  0     161.944016
1     161.944016
2     161.94...   
2  0     166.998447
1     167.065036
2     167.06...   
3  0     147.13808
1     147.13808
2     147.1380...   
4  0     155.539272
1     155.539272
2     155.53...   

        libvirt_domain_block_stats_write_bytes_total  \
0  0     5.335634e+09
1     5.335634e+09
2     5....   
1  0     5.486572e+09
1     5.486572e+09
2     5....   
2  0     6.043132e+09
1     6.043615e+09
2     6....   
3  0     5.431456e+09
1     5.431472e+09
2     5....   
4  0     5.811597e+09
1     5.811597e+09
2     5....   

     libvirt_domain_block_stats_write_requests_total  \
0  0     75123.0
1     75123.0
2     75191.0
3   ...   
1  0     92736.0
1     92736.0
2     92736.0
3   ...   
2  0     111134.0
1     111204.0
2     111217.0
3...   
3  0     82255.0
1     82258.0
2     82259.0
3   ...   
4  0     111165.0
1     111165.0
2     111165.0
3...   

  libvirt_domain_block_stats_write_time_seconds_total  \
0  0     136.586810
1     136.586810
2     136.61...    
1  0     214.482965
1     214.482965
2     214.48...    
2  0     226.401918
1     226.440294
2     226.44...    
3  0     114.547265
1     114.548299
2     114.54...    
4  0     139.674985
1     139.674985
2     139.67...    

          libvirt_domain_info_cpu_time_seconds_total  \
0  0     7242.05
1     7245.63
2     7249.16
3   ...   
1  0     13493.85
1     13642.20
2     13793.26
3...   
2  0     32085.56
1     32089.23
2     32092.89
3...   
3  0     7192.28
1     7195.84
2     7199.23
3   ...   
4  0     12577.01
1     12728.06
2     12880.53
3...   

              libvirt_domain_info_memory_usage_bytes  ...  \
0  0     1.073742e+09
1     1.073742e+09
2     1....  ...   
1  0     1.073742e+09
1     1.073742e+09
2     1....  ...   
2  0     1.073742e+09
1     1.073742e+09
2     1....  ...   
3  0     1.073742e+09
1     1.073742e+09
2     1....  ...   
4  0     1.073742e+09
1     1.073742e+09
2     1....  ...   

  libvirt_domain_interface_stats_transmit_packets_total   \
0  0     52300.0
1     52321.0
2     52371.0
3   ...       
1  0     82356.0
1     82380.0
2     82395.0
3   ...       
2  0     115307.0
1     115318.0
2     115325.0
3...       
3  0     51890.0
1     51908.0
2     51936.0
3   ...       
4  0     82599.0
1     82620.0
2     82643.0
3   ...       

        libvirt_domain_memory_stats_disk_cache_bytes  \
0  0     0.0
1     0.0
2     0.0
3     0.0
4     ...   
1  0     0.0
1     0.0
2     0.0
3     0.0
4     ...   
2  0     0.0
1     0.0
2     0.0
3     0.0
4     ...   
3  0    

In [ ]:
y_train = np.array(([1 for i in range(6)] + [0 for i in range(3)]) * 3)
X_train = sk_frame

#### Считывание данных, полученных с помощью Prometheus с виртуальных машин (test)

In [ ]:
fd_test = []
y_test = np.array([])
for root, dirs, files in os.walk('/content/drive/MyDrive/curs_work/test/'):  
    for f in files:
        print(f)
        fd_test.append(pd.read_csv('/content/drive/MyDrive/curs_work/test/' + f, index_col=0))
        if f == 'instance-00006400.csv' or f == 'instance-000063fe.csv' or f == 'instance-00006401.csv':
            y_test = np.append(y_test, 1)
        else:
            y_test = np.append(y_test, 0)

instance-0000096b.csv
instance-000063fe.csv
instance-000060f1.csv
instance-0000094d.csv
instance-0000055f.csv
instance-0000054d.csv
instance-000002cb.csv
instance-000001c3.csv
instance-000002bf.csv
instance-00006479.csv
instance-00006400.csv
instance-00000962.csv
instance-00006401.csv
instance-00005145.csv
instance-00000968.csv
instance-00000932.csv
instance-00000607.csv
instance-00000538.csv
instance-00000409.csv
instance-00000286.csv


##### Преобразование в sktime DataFrame

In [ ]:
X_test = from_2d_array_to_nested(fd_test[0].T).T
for i in np.arange(1, len(fd_test)):
    X_test = X_test.append(from_2d_array_to_nested(fd_test[i].T).T)
X_test.columns = fd_test[0].columns
X_test = X_test.reset_index(drop=True)
X_test.head(26)

libvirt_domain_block_stats_flush_requests_total  \
0   0     1924658.0
1     1924658.0
2     1924658....   
1   0     207915675.0
1     207915685.0
2     2079...   
2   0     416490.0
1     416516.0
2     416546.0
3...   
3   0     1864439.0
1     1864443.0
2     1864445....   
4   0     2185480.0
1     2185484.0
2     2185488....   
5   0     2573707.0
1     2573707.0
2     2573707....   
6   0     1252291.0
1     1252291.0
2     1252291....   
7   0     88740296.0
1     88740422.0
2     887406...   
8   0     1017857.0
1     1017857.0
2     1017861....   
9   0     1036021.0
1     1036047.0
2     1036080....   
10  0     209357499.0
1     209357501.0
2     2093...   
11  0     241058.0
1     241058.0
2     241058.0
3...   
12  0     237063814.0
1     238532338.0
2     2399...   
13  0     1037769.0
1     1037769.0
2     1037769....   
14  0     12667643.0
1     12667663.0
2     126676...   
15  0     757613.0
1     757613.0
2     757613.0
3...   
16  0     13099272.0
1     13099288.0
2     130993...   
17  0     647597.0
1     647597.0
2     647597.0
3...   
18  0     4150850.0
1     4150856.0
2     4150866....   
19  0     60844.0
1     60844.0
2     60846.0
3   ...   

   libvirt_domain_block_stats_flush_time_seconds_total  \
0   0     278.026807
1     278.026807
2     278.02...    
1   0     1901.827081
1     1901.828116
2     1901...    
2   0     351.748647
1     351.750412
2     351.75...    
3   0     454.507718
1     454.508690
2     454.50...    
4   0     274.517765
1     274.518062
2     274.51...    
5   0     350.439009
1     350.439009
2     350.43...    
6   0     125.051482
1     125.051482
2     125.05...    
7   0     11593.453459
1     11593.465196
2     11...    
8   0     244.152348
1     244.152348
2     244.15...    
9   0     345.959152
1     345.963141
2     345.96...    
10  0     1761.402912
1     1761.403028
2     1761...    
11  0     57.529403
1     57.529403
2     57.52940...    
12  0     2005.014508
1     2017.728995
2     2028...    
13  0     1428.741729
1     1428.741729
2     1428...    
14  0     21478.269808
1     21478.270715
2     21...    
15  0     58.857145
1     58.857145
2     58.85714...    
16  0     37678.642629
1     37678.645927
2     37...    
17  0     35.895515
1     35.895515
2     35.89551...    
18  0     667.171139
1     667.171755
2     667.17...    
19  0     7.044528
1     7.044528
2     7.044806
3...    

          libvirt_domain_block_stats_read_bytes_total  \
0   0     1.116498e+10
1     1.116498e+10
2     1....   
1   0     3.666002e+09
1     3.666002e+09
2     3....   
2   0     1.908914e+09
1     1.908914e+09
2     1....   
3   0     7.788868e+10
1     7.788868e+10
2     7....   
4   0     1.166085e+09
1     1.166085e+09
2     1....   
5   0     8.743032e+12
1     8.743032e+12
2     8....   
6   0     3.760165e+09
1     3.760165e+09
2     3....   
7   0     1.184182e+11
1     1.184198e+11
2     1....   
8   0     468919808.0
1     468919808.0
2     4689...   
9   0     690943488.0
1     690943488.0
2     6909...   
10  0     2.970100e+09
1     2.970100e+09
2     2....   
11  0     162070528.0
1     162070528.0
2     1620...   
12  0     4.618905e+09
1     4.618905e+09
2     4....   
13  0     1.279981e+11
1     1.279981e+11
2     1....   
14  0     4.217924e+10
1     4.217924e+10
2     4....   
15  0     5.117197e+09
1     5.117197e+09
2     5....   
16  0     8.277405e+10
1     8.277405e+10
2     8....   
17  0     2.859436e+09
1     2.859436e+09
2     2....   
18  0     663261184.0
1     663261184.0
2     6632...   
19  0     847638016.0
1     847638016.0
2     8476...   

       libvirt_domain_block_stats_read_requests_total  \
0   0     1019192.0
1     1019192.0
2     1019192....   
1   0     140992.0
1     140992.0
2     140992.0
3...   
2   0     110227.0
1     110227.0
2     110227.0
3...   
3   0     651847.0
1     651847.0
2     651847.0
3...   
4   0     118743.0
1     118743.0
2     118743.0
3...   
5   0     19931368.0
1     19931368.0
2     19931

In [ ]:
for i in range(len(X_test)):
    for j in range(len(X_test.columns)):
        print(i,j, end = " ")
        
print()
print(X_test.iloc[9,9])

# cc.fit_transform(X_test.iloc[:, [0,9]])

0 0 0 1 0 2 0 3 0 4 0 5 0 6 0 7 0 8 0 9 0 10 0 11 0 12 0 13 0 14 0 15 0 16 0 17 0 18 0 19 0 20 0 21 0 22 0 23 0 24 0 25 0 26 1 0 1 1 1 2 1 3 1 4 1 5 1 6 1 7 1 8 1 9 1 10 1 11 1 12 1 13 1 14 1 15 1 16 1 17 1 18 1 19 1 20 1 21 1 22 1 23 1 24 1 25 1 26 2 0 2 1 2 2 2 3 2 4 2 5 2 6 2 7 2 8 2 9 2 10 2 11 2 12 2 13 2 14 2 15 2 16 2 17 2 18 2 19 2 20 2 21 2 22 2 23 2 24 2 25 2 26 3 0 3 1 3 2 3 3 3 4 3 5 3 6 3 7 3 8 3 9 3 10 3 11 3 12 3 13 3 14 3 15 3 16 3 17 3 18 3 19 3 20 3 21 3 22 3 23 3 24 3 25 3 26 4 0 4 1 4 2 4 3 4 4 4 5 4 6 4 7 4 8 4 9 4 10 4 11 4 12 4 13 4 14 4 15 4 16 4 17 4 18 4 19 4 20 4 21 4 22 4 23 4 24 4 25 4 26 5 0 5 1 5 2 5 3 5 4 5 5 5 6 5 7 5 8 5 9 5 10 5 11 5 12 5 13 5 14 5 15 5 16 5 17 5 18 5 19 5 20 5 21 5 22 5 23 5 24 5 25 5 26 6 0 6 1 6 2 6 3 6 4 6 5 6 6 6 7 6 8 6 9 6 10 6 11 6 12 6 13 6 14 6 15 6 16 6 17 6 18 6 19 6 20 6 21 6 22 6 23 6 24 6 25 6 26 7 0 7 1 7 2 7 3 7 4 7 5 7 6 7 7 7 8 7 9 7 10 7 11 7 12 7 13 7 14 7 15 7 16 7 17 7 18 7 19 7 20 7 21 7 22 7 23 7 24 7 25 7 26 

#### Обучение моделей

Функция делящая n элементов на нужное количество фолдов

In [ ]:
def kfold_split(num_objects, num_folds):
    ans = []
    count = num_objects // num_folds
    mas = np.arange(num_objects)
    i = 0
    for i in range(0, count * (num_folds - 1), count):
        ans.append((np.hstack([mas[:i], mas[i+count:]]), mas[i:i + count]))
    else:
        i += count
        ans.append((mas[:i], mas[i:]))
    return ans

### Анализ признаков 

Сначала проведем кросс-валидацию по каждому столбцу отдельно и посмотрим какие столбцы дудут наилучший результат

##### Отбор через TimeSeriesForestClassifier

In [ ]:
tf_ans = dict()
folds = kfold_split(len(X_train), 3)
for i in range(27):
    for k in np.logspace(1, 3, 10):
        metrics = 0
        for datas in folds:
            X_train_cv = X_train.iloc[datas[0]]
            y_train_cv = y_train[datas[0]]
            X_test_cv = X_train.iloc[datas[1]]
            y_test_cv = y_train[datas[1]]
            clf = ColumnEnsembleClassifier(
                estimators=[
                    ("TSF", TimeSeriesForestClassifier(n_estimators=int(k)), [i]),
                ]
            )
            clf.fit(X_train_cv, y_train_cv)
            metrics += clf.score(X_test_cv, y_test_cv)
        tf_ans[(i, int(k))] = metrics / len(folds)

Посмотрим на столбцы, по которым модель наиболее эффективно определяет зараженность ВМ

In [ ]:
final_dict = {k:v for k, v in tf_ans.items() if v > 0.7}
tf_cols = list(set(i[0] for i in list(final_dict.keys())))
sk_frame.columns[tf_cols]

Index(['libvirt_domain_block_stats_flush_requests_total',
       'libvirt_domain_block_stats_flush_time_seconds_total',
       'libvirt_domain_block_stats_read_bytes_total',
       'libvirt_domain_block_stats_read_requests_total',
       'libvirt_domain_block_stats_read_time_seconds_total',
       'libvirt_domain_block_stats_write_bytes_total',
       'libvirt_domain_block_stats_write_requests_total',
       'libvirt_domain_block_stats_write_time_seconds_total',
       'libvirt_domain_info_cpu_time_seconds_total',
       'libvirt_domain_interface_stats_receive_bytes_total',
       'libvirt_domain_interface_stats_receive_packets_total',
       'libvirt_domain_interface_stats_transmit_bytes_total',
       'libvirt_domain_interface_stats_transmit_packets_total ',
       'libvirt_domain_memory_stats_major_fault_total',
       'libvirt_domain_memory_stats_minor_fault_total',
       'libvirt_domain_memory_stats_rss_bytes',
       'libvirt_domain_memory_stats_unused_bytes',
       'libvirt_do

##### Отбор через KNeighborsTimeSeriesClassifier

In [ ]:
knn_ans = dict()
folds = kfold_split(len(X_train), 3)
for i in range(27):
    for k in [1, 3, 5, 7, 9]:
        metrics = 0
        for datas in folds:
            X_train_cv = X_train.iloc[datas[0]]
            y_train_cv = y_train[datas[0]]
            X_test_cv = X_train.iloc[datas[1]]
            y_test_cv = y_train[datas[1]]
            clf = ColumnEnsembleClassifier(
                estimators=[
                    ("TSF", KNeighborsTimeSeriesClassifier(n_neighbors=int(k)), [i]),
                ]
            )
            clf.fit(X_train_cv, y_train_cv)
            metrics += clf.score(X_test_cv, y_test_cv)
        knn_ans[(i, int(k))] = metrics / len(folds)

Посмотрим на столбцы, по которым модель наиболее эффективно определяет зараженность ВМ

In [ ]:
final_dict = {k:v for k, v in knn_ans.items() if v > 0.7}
knn_cols = list(set(i[0] for i in list(final_dict.keys())))
sk_frame.columns[knn_cols]

Index(['libvirt_domain_block_stats_flush_requests_total',
       'libvirt_domain_block_stats_flush_time_seconds_total',
       'libvirt_domain_block_stats_read_bytes_total',
       'libvirt_domain_block_stats_read_requests_total',
       'libvirt_domain_block_stats_read_time_seconds_total',
       'libvirt_domain_block_stats_write_bytes_total',
       'libvirt_domain_block_stats_write_requests_total',
       'libvirt_domain_block_stats_write_time_seconds_total',
       'libvirt_domain_info_cpu_time_seconds_total',
       'libvirt_domain_interface_stats_receive_bytes_total',
       'libvirt_domain_interface_stats_receive_packets_total',
       'libvirt_domain_interface_stats_transmit_bytes_total',
       'libvirt_domain_interface_stats_transmit_packets_total ',
       'libvirt_domain_memory_stats_major_fault_total',
       'libvirt_domain_memory_stats_minor_fault_total',
       'libvirt_domain_memory_stats_rss_bytes',
       'libvirt_domain_memory_stats_unused_bytes',
       'libvirt_do

##### Агрегирование результатов отбора с двух разных моделей

Таким образом мы получили наиболее информативные столбцы для отслеживания.

In [ ]:
inter = list(set(tf_cols).intersection(knn_cols))
sk_frame.columns[inter]

Index(['libvirt_domain_block_stats_flush_requests_total',
       'libvirt_domain_block_stats_flush_time_seconds_total',
       'libvirt_domain_block_stats_read_bytes_total',
       'libvirt_domain_block_stats_read_requests_total',
       'libvirt_domain_block_stats_read_time_seconds_total',
       'libvirt_domain_block_stats_write_bytes_total',
       'libvirt_domain_block_stats_write_requests_total',
       'libvirt_domain_block_stats_write_time_seconds_total',
       'libvirt_domain_info_cpu_time_seconds_total',
       'libvirt_domain_interface_stats_receive_bytes_total',
       'libvirt_domain_interface_stats_receive_packets_total',
       'libvirt_domain_interface_stats_transmit_bytes_total',
       'libvirt_domain_interface_stats_transmit_packets_total ',
       'libvirt_domain_memory_stats_major_fault_total',
       'libvirt_domain_memory_stats_minor_fault_total',
       'libvirt_domain_memory_stats_rss_bytes',
       'libvirt_domain_memory_stats_unused_bytes',
       'libvirt_do

### Обучение и тестирование моделей

#### ColumnConcatenator

Мы можем объединить многомерные временные ряды/панельные данные в длинные одномерные временные ряды/панели, а затем применить классификатор к одномерным данным. 

##### TimeSeriesForestClassifier

1) кросс-валидация

In [ ]:
ans = {}
folds = kfold_split(len(X_train), 3)
for k in np.logspace(1, 3, 10):
    metrics = 0
    for datas in folds:
        X_train_cv = X_train.iloc[:, inter].iloc[datas[0]]
        y_train_cv = y_train[datas[0]]
        X_test_cv = X_train.iloc[:, inter].iloc[datas[1]]
        y_test_cv = y_train[datas[1]]
        steps = [
            ("concatenate", ColumnConcatenator()),
            ("classify", TimeSeriesForestClassifier(n_estimators=int(k))),
        ]        
        clf = Pipeline(steps)
        clf.fit(X_train_cv, y_train_cv)
        metrics += clf.score(X_test_cv, y_test_cv)
    ans[int(k)] = metrics / len(folds)


2) поиск наилучшего значения

In [ ]:
max_val = max(ans.values())
final_dict = {k:v for k, v in ans.items() if v == max_val}
final_dict

{10: 1.0,
 16: 1.0,
 27: 1.0,
 46: 1.0,
 77: 1.0,
 129: 1.0,
 215: 1.0,
 359: 1.0,
 599: 1.0,
 1000: 1.0}

3) обучение и тест

In [ ]:
steps = [
    ("concatenate", ColumnConcatenator()),
    ("classify", TimeSeriesForestClassifier(n_estimators=100)),
]        
clf = Pipeline(steps)
clf.fit(X_train.iloc[:, inter], y_train)
clf.score(X_test.iloc[:, inter], y_test)

0.15

In [ ]:
clf.predict(X_test.iloc[:, inter]), y_test

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
        0., 0., 0.]))

##### KNeighborsTimeSeriesClassifier

1) кросс-валидация

In [ ]:
ans = {}
folds = kfold_split(len(X_train), 3)
for k in [1,3,5,7,9]:
    metrics = 0
    for datas in folds:
        X_train_cv = X_train.iloc[:, inter].iloc[datas[0]]
        y_train_cv = y_train[datas[0]]
        X_test_cv = X_train.iloc[:, inter].iloc[datas[1]]
        y_test_cv = y_train[datas[1]]
        steps = [
            ("concatenate", ColumnConcatenator()),
            ("classify", KNeighborsTimeSeriesClassifier(n_neighbors=int(k))),
        ]        
        clf = Pipeline(steps)
        clf.fit(X_train_cv, y_train_cv)
        metrics += clf.score(X_test_cv, y_test_cv)
    ans[int(k)] = metrics / len(folds)


2) поиск наилучшего значения k

In [ ]:
max_val = max(ans.values())
final_dict = {k:v for k, v in ans.items() if v == max_val}
final_dict

{1: 0.9259259259259259}

3) обучение и тест

In [ ]:
steps = [
    ("concatenate", ColumnConcatenator()),
    ("classify", KNeighborsTimeSeriesClassifier(n_neighbors=1)),
]        
clf = Pipeline(steps)
clf.fit(X_train.iloc[:, inter], y_train)
clf.score(X_test.iloc[:, inter], y_test)

0.2

In [ ]:
clf.predict(X_test.iloc[:, inter]), y_test

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
        0., 0., 0.]))

#### ColumnEnsembleClassifier

Мы также можем подобрать один классификатор для определенных столбцов временных рядов, а затем агрегировать их прогнозы.

##### TimeSeriesForestClassifier

1) Кросс валидация

In [ ]:
ans = {}
folds = kfold_split(len(X_train), 3)
for k in np.logspace(1, 3, 10):
    metrics = 0
    for datas in folds:
        X_train_cv = X_train.iloc[:, inter].iloc[datas[0]]
        y_train_cv = y_train[datas[0]]
        X_test_cv = X_train.iloc[:, inter].iloc[datas[1]]
        y_test_cv = y_train[datas[1]]
        clf = ColumnEnsembleClassifier(
            estimators=[
                ("TSF" + str(i), TimeSeriesForestClassifier(n_estimators=int(k)), [i]) for i in range(len(inter))
            ]
        )
        clf.fit(X_train_cv, y_train_cv)
        metrics += clf.score(X_test_cv, y_test_cv)
    ans[int(k)] = metrics / len(folds)

2) Поиск наилучшего k

In [ ]:
max_val = max(ans.values())
final_dict = {k:v for k, v in ans.items() if v == max_val}
final_dict

{10: 1.0,
 16: 1.0,
 27: 1.0,
 46: 1.0,
 77: 1.0,
 129: 1.0,
 215: 1.0,
 359: 1.0,
 599: 1.0,
 1000: 1.0}

3) Обучение и тест

In [ ]:
clf = ColumnEnsembleClassifier(
    estimators=[
        ("TSF" + str(i), TimeSeriesForestClassifier(n_estimators=int(100)), [i]) for i in range(len(inter))
    ]
)
clf.fit(X_train.iloc[:, inter], y_train)
clf.score(X_test.iloc[:, inter], y_test)

0.2

In [ ]:
clf.predict(X_test.iloc[:, inter]), y_test

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]),
 array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
        0., 0., 0.]))

##### KNeighborsTimeSeriesClassifier

1) Кросс валидация

In [ ]:
ans = {}
folds = kfold_split(len(X_train), 3)
for k in [1,3,5,7,9]:
    metrics = 0
    for datas in folds:
        X_train_cv = X_train.iloc[:, inter].iloc[datas[0]]
        y_train_cv = y_train[datas[0]]
        X_test_cv = X_train.iloc[:, inter].iloc[datas[1]]
        y_test_cv = y_train[datas[1]]
        clf = ColumnEnsembleClassifier(
            estimators=[
                ("TSF" + str(i), KNeighborsTimeSeriesClassifier(n_neighbors=int(k)), [i]) for i in range(len(inter))
            ]

        )
        clf.fit(X_train_cv, y_train_cv)
        metrics += clf.score(X_test_cv, y_test_cv)
    ans[int(k)] = metrics / len(folds)

2) Поиск наилучшего k

In [ ]:
max_val = max(ans.values())
final_dict = {k:v for k, v in ans.items() if v == max_val}
final_dict

{1: 1.0, 3: 1.0}

3) Обучение и тест

In [ ]:
clf = ColumnEnsembleClassifier(
    estimators=[
        ("TSF" + str(i), KNeighborsTimeSeriesClassifier(n_neighbors=int(1)), [i]) for i in range(len(inter))
    ]
)
clf.fit(X_train.iloc[:, inter], y_train)
clf.score(X_test.iloc[:, inter], y_test)

0.15

In [ ]:
clf.predict(X_test.iloc[:, inter]), y_test

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
        0., 0., 0.]))